### ISSUE TITLE
Multiple Devices in single preset.

### ISSUE THREAD

**Issue by jonpauldavies** [martinpavlas/electra.one#31]
This image in the manual suggests that you can have multiple devices in the same preset.

![image](https://i.imgur.com/JvuDnR0l.png)

The editor doesnt seem to support this, and hand creating presets with multiple devices doesnt work either. Has this feature been removed?

**Comment by martinpavlas** [comment]
hi Jon,

I am about to update the manual. Editor now supports 12 devices. In short, before the update is done: click the "<" arrow in the "Device", a list of all available Devices will show up. There pick the device you want to work with.

**Comment by jonpauldavies** [comment]
So you can only have one device per preset?

**Comment by martinpavlas** [comment]
you can have 12 devices per preset. which means that even one page may have filter controls for up to 12 synths. What is confusing you is probably the fact that you can see controls for one device in the side bar at the time. I will update the document today so that there is no confusion about how it works.

**Comment by martinpavlas** [comment]
Please refer to documentation at https://docs.electra.one/ for details.
